{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "opensearch.uname" . }}-service-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "opensearch.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "opensearch.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: {{ .Values.service.httpPortName | default "http" }}
    interval: {{ .Values.serviceMonitor.interval }}
    path: {{ .Values.serviceMonitor.path }}
    {{- if .Values.serviceMonitor.basicAuth }}
    basicAuth:
      username: 
        name: {{ .Values.serviceMonitor.basicAuth.username.secretName}}
        key: {{ .Values.serviceMonitor.basicAuth.username.secretKey}}
      password:
        name: {{ .Values.serviceMonitor.basicAuth.password.secretName}}
        key: {{ .Values.serviceMonitor.basicAuth.password.secretKey}}
    {{- end }}
{{- end }}
